### ISSUE TITLE
Ajax bug or documentation typo

### ISSUE THREAD

**Issue by mijdavis2** [gi0baro/weppy#138]
Using the ajax example from the [templates docs](https://github.com/gi0baro/weppy/blob/master/docs/templates.md#included-helpers):

```python
@app.route()
def my_ajaxf():
    return "$('#target').html('something');"
```
Ensured I'm using the helpers:
```html
<script type="text/javascript" src="/__weppy__/jquery.min.js"></script>
<script type="text/javascript" src="/__weppy__/helpers.js"></script>

<div id="target"></div>
<script type="text/javascript">
  ajax({{=url('my_ajaxf'), [], ':eval'}});
</script>
```
**Getting this error:**
```TypeError: write() takes from 2 to 3 positional arguments but 4 were given```

**Full traceback:**
Traceback (most recent call last):
  File "/.../python3.5/site-packages/weppy/wsgi.py", line 94, in error_handler
    return static_handler(app, environ, start_response)
  File "/.../python3.5/site-packages/weppy/wsgi.py", line 86, in static_handler
    return dynamic_handler(app, environ, start_response)
  File "/.../python3.5/site-packages/weppy/wsgi.py", line 35, in dynamic_handler
    app.route.dispatch()
  File "/.../python3.5/site-packages/weppy/expose.py", line 231, in dispatch
    route.func(**reqargs)
  File "/.../python3.5/site-packages/weppy/handlers.py", line 24, in handled_function
    output = handler.wrap_call(f)(*args, **kwargs)
  File "/.../python3.5/site-packages/weppy/expose.py", line 266, in wrap
    self.route.template, output)
  File "/.../python3.5/site-packages/weppy/templating/core.py", line 154, in render
    return templater.render(tsource, tpath, tname, context)
  File "/.../python3.5/site-packages/weppy/templating/core.py", line 131, in render
    make_traceback(exc_info, template_ref)
  File "/.../python3.5/site-packages/weppy/debug.py", line 262, in make_traceback
    reraise(exc_type, exc_value, tb)
  File "/.../python3.5/site-packages/weppy/_compat.py", line 93, in reraise
    raise value.with_traceback(tb)
  File "/.../weppy_mvc_demo/weppy_mvc_demo/views/tour/ajax.haml.html", line 5, in <module>
    ajax({{=url('my_ajaxf'), [], ':eval'}});
TypeError: write() takes from 2 to 3 positional arguments but 4 were given

Any ideas? Thanks in advanced.

**Comment by gi0baro** [comment]
@mijdavis2 looks like a documentation typo.

The brackets should be closed after the url in the `ajax` function call:
```html
<script type="text/javascript">
  ajax({{=url('my_ajaxf')}}, [], ':eval');
</script>
```

Will fix the docs asap.

**Comment by mijdavis2** [comment]
Ah of course. That's definitely causing the error! 

Still a little bit off. Looks like we need to wrap the braces in ```"``` as well or ajax/jquery thinks it's an invalid regex statement:

```html
<script type="text/javascript">
  ajax("{{=url('my_ajaxf')}}", [], ':eval');
</script>
```

PR for the fix coming up.
