### ISSUE TITLE
ImportError: cannot import name 'SessionManager'

### ISSUE THREAD

**Issue by josejachuf** [gi0baro/weppy#205]
weppy (1.1.2)

from weppy.sessions import SessionManager
ImportError: cannot import name 'SessionManager'

**Comment by gi0baro** [comment]
@josejachuf can you post the whole traceback?

**Comment by josejachuf** [comment]
Hi @gi0baro 

[venv36] jose@cx:~/trabajos/apalfadit/cepa19env/cepa % weppy --app=cepa run
Traceback (most recent call last):
  File "/usr/home/jose/trabajos/apalfadit/cepa19env/venv36/bin/weppy", line 11, in <module>
    sys.exit(main())
  File "/usr/home/jose/trabajos/apalfadit/cepa19env/venv36/lib/python3.6/site-packages/weppy/cli.py", line 395, in main
    cli.main(args=args, prog_name=name)
  File "/usr/home/jose/trabajos/apalfadit/cepa19env/venv36/lib/python3.6/site-packages/weppy/cli.py", line 240, in main
    return click.Group.main(self, *args, **kwargs)
  File "/usr/home/jose/trabajos/apalfadit/cepa19env/venv36/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/home/jose/trabajos/apalfadit/cepa19env/venv36/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/home/jose/trabajos/apalfadit/cepa19env/venv36/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/home/jose/trabajos/apalfadit/cepa19env/venv36/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/home/jose/trabajos/apalfadit/cepa19env/venv36/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/home/jose/trabajos/apalfadit/cepa19env/venv36/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/home/jose/trabajos/apalfadit/cepa19env/venv36/lib/python3.6/site-packages/weppy/cli.py", line 254, in run_command
    app = info.load_app()
  File "/usr/home/jose/trabajos/apalfadit/cepa19env/venv36/lib/python3.6/site-packages/weppy/cli.py", line 157, in load_app
    a = locate_app(self.app_import_path)
  File "/usr/home/jose/trabajos/apalfadit/cepa19env/venv36/lib/python3.6/site-packages/weppy/cli.py", line 102, in locate_app
    module, mod, app_obj = get_app_module(app_id)
  File "/usr/home/jose/trabajos/apalfadit/cepa19env/venv36/lib/python3.6/site-packages/weppy/cli.py", line 95, in get_app_module
    __import__(module)
  File "./cepa/__init__.py", line 10, in <module>
    from weppy.sessions import SessionManager
ImportError: cannot import name 'SessionManager'

**Comment by gi0baro** [comment]
@josejachuf `SessionManager` will be available in 1.2, 1.1.2 is just a bugfix release over 1.1.1
If you're using 1.2-dev it includes the fixes of 1.1.2, so stay with that.

**Comment by josejachuf** [comment]
Ok, I thought it was in 1.1.2. Thank you
