### ISSUE TITLE
Attempting to use database in another process (python multiprocessing)

### ISSUE THREAD

**Issue by guy881** [gi0baro/weppy#214]
I am using Weppy + Weppy REST with PostgreSQL, what I am trying to achieve is concurrent access to database using python multiprocessing module.

This is my endpoint of Scan API:
```python
@scans.create()
def scans_new():
    attrs = scans.parse_params()
    resp = Scan.create(**attrs)
    serialized_scan = scans.serialize_one(resp.id)
    pool = Pool()
    pool.apply_async(begin_scan, args=[resp.id], callback=scan_finished_callback)
    pool.close()

    return serialized_scan
```
`begin_scan` is a function that is called in separate process, so I am opening new database connection in this way:
```python
def begin_scan(scan_id):
    app = App('app')
    app.config_from_yaml('db.yml', 'db')
    db = Database(app)
    db.define_models(SpectrumAnalyzer, FieldProbe, Scan, ScanResult)
    with db.connection():
        # I can read from database
        scan = Scan.get(scan_id)
        result = ScanResult.create(scan=scan_id)  # I can save too
        db.commit()
```
After this I am trying to fetch result via API, and then I get exception:
```
> ERROR in wsgi [/home/stevens/.virtualenvs/near-field-scanner-web/lib/python3.6/site-packages/weppy/wsgi.py:110]:
Application exception:
Traceback (most recent call last):
  File "/home/stevens/.virtualenvs/near-field-scanner-web/lib/python3.6/site-packages/weppy/wsgi.py", line 95, in error_handler
    return app.common_static_handler(app, environ, start_response)
  File "/home/stevens/.virtualenvs/near-field-scanner-web/lib/python3.6/site-packages/weppy/wsgi.py", line 68, in static_handler
    return dynamic_handler(app, environ, start_response)
  File "/home/stevens/.virtualenvs/near-field-scanner-web/lib/python3.6/site-packages/weppy/wsgi.py", line 31, in dynamic_handler
    app.route.dispatch()
  File "/home/stevens/.virtualenvs/near-field-scanner-web/lib/python3.6/site-packages/weppy/expose.py", line 265, in dispatch
    route.f(**reqargs)
  File "/home/stevens/.virtualenvs/near-field-scanner-web/lib/python3.6/site-packages/weppy/pipeline.py", line 26, in pipe_flow
    output = link.pipe.pipe(link.f, **kwargs)
  File "/home/stevens/.virtualenvs/near-field-scanner-web/lib/python3.6/site-packages/weppy/expose.py", line 426, in pipe
    output = next_pipe(**kwargs)
  File "/home/stevens/.virtualenvs/near-field-scanner-web/lib/python3.6/site-packages/weppy/pipeline.py", line 26, in pipe_flow
    output = link.pipe.pipe(link.f, **kwargs)
  File "/home/stevens/.virtualenvs/near-field-scanner-web/lib/python3.6/site-packages/weppy/pipeline.py", line 53, in pipe
    return next_pipe(**kwargs)
  File "/home/stevens/.virtualenvs/near-field-scanner-web/lib/python3.6/site-packages/weppy/pipeline.py", line 26, in pipe_flow
    output = link.pipe.pipe(link.f, **kwargs)
  File "/home/stevens/.virtualenvs/near-field-scanner-web/lib/python3.6/site-packages/weppy/pipeline.py", line 53, in pipe
    return next_pipe(**kwargs)
  File "/home/stevens/.virtualenvs/near-field-scanner-web/lib/python3.6/site-packages/weppy/pipeline.py", line 26, in pipe_flow
    output = link.pipe.pipe(link.f, **kwargs)
  File "/home/stevens/.virtualenvs/near-field-scanner-web/lib/python3.6/site-packages/weppy/tools/service.py", line 39, in pipe
    return self.procedure(next_pipe, **kwargs)
  File "/home/stevens/.virtualenvs/near-field-scanner-web/lib/python3.6/site-packages/weppy/tools/service.py", line 30, in json
    data = f(**kwargs)
  File "/home/stevens/.virtualenvs/near-field-scanner-web/lib/python3.6/site-packages/weppy/pipeline.py", line 26, in pipe_flow
    output = link.pipe.pipe(link.f, **kwargs)
  File "/home/stevens/.virtualenvs/near-field-scanner-web/lib/python3.6/site-packages/weppy_rest/helpers.py", line 23, in pipe
    return next_pipe(**kwargs)
  File "/home/stevens/.virtualenvs/near-field-scanner-web/lib/python3.6/site-packages/weppy/pipeline.py", line 26, in pipe_flow
    output = link.pipe.pipe(link.f, **kwargs)
  File "/home/stevens/.virtualenvs/near-field-scanner-web/lib/python3.6/site-packages/weppy_rest/helpers.py", line 35, in pipe
    self.fetch_record(kwargs)
  File "/home/stevens/.virtualenvs/near-field-scanner-web/lib/python3.6/site-packages/weppy_rest/helpers.py", line 43, in fetch_record
    ).select(self.mod.model.table.ALL).first()
  File "/home/stevens/.virtualenvs/near-field-scanner-web/lib/python3.6/site-packages/weppy/orm/objects.py", line 310, in select
    return super(Set, self).select(*fields, **options)
  File "/home/stevens/.virtualenvs/near-field-scanner-web/lib/python3.6/site-packages/pydal/objects.py", line 2210, in select
    return adapter.select(self.query, fields, attributes)
  File "/home/stevens/.virtualenvs/near-field-scanner-web/lib/python3.6/site-packages/pydal/adapters/base.py", line 760, in select
    return self._select_aux(sql, fields, attributes, colnames)
  File "/home/stevens/.virtualenvs/near-field-scanner-web/lib/python3.6/site-packages/pydal/adapters/base.py", line 716, in _select_aux
    rows = self._select_aux_execute(sql)
  File "/home/stevens/.virtualenvs/near-field-scanner-web/lib/python3.6/site-packages/pydal/adapters/base.py", line 710, in _select_aux_execute
    self.execute(sql)
  File "/home/stevens/.virtualenvs/near-field-scanner-web/lib/python3.6/site-packages/pydal/adapters/__init__.py", line 65, in wrap
    raise ValueError(args[1])
ValueError: SELECT "Scans"."id", "Scans"."name", "Scans"."date", "Scans"."kind", "Scans"."min_frequency", "Scans"."max_frequency", "Scans"."min_frequency_unit", "Scans"."max_frequency_unit", "Scans"."min_x", "Scans"."min_y", "Scans"."min_z", "Scans"."max_x", "Scans"."max_y", "Scans"."max_z", "Scans"."pcb_filename", "Scans"."status", "Scans"."progress", "Scans"."analyzer", "Scans"."probe" FROM "Scans" WHERE (("Scans"."id" IS NOT NULL) AND ("Scans"."id" = 37));
```
New `ScanResult` is actually in database and after I reload Weppy server exception is not raised and I can successfully get it via API. I guess it is some problem with database connections, but I am not sure how it should be done in Weppy. Any help would be very welcome.

**Comment by gi0baro** [comment]
@guy881 I'm not sure to understand why you're trying to deal with `multiprocessing` directly inside your code. Why not to put something like uwsgi with multiple processes in front of weppy?

Can you explain what's your goal?

**Comment by guy881** [comment]
Sorry, I could have explained it before. Well, basically, function `begin_scan` will be communicating with Near Field Scanner and saving a progress of Scan to database, so it will take a long time. But I have to return response after saving scan model in `@scans.create()`, so I can redirect user to another view (where he can track progress of scanning).

I also tried using Celery for this purpose, but results were similar, so I tried again with multiprocessing.

**Comment by gi0baro** [comment]
Ok, this is how I usually do for background staffs:

```python
app = App('app')
app.config_from_yaml('db.yml', 'db')
db = Database(app)
db.define_models(SpectrumAnalyzer, FieldProbe, Scan, ScanResult)
celery = Celery()

@celery.task
def my_background_stuff():
    with db.connection():
        # do work
```

So, being you, I will use celery and void to re-define the whole app and database inside the background things.

Anyway the traceback you posted seems coming from the GET request of a single record, so I think it's not involved in this flow. Are you sure the name of the table is "Scans" with the uppercase S?

**Comment by guy881** [comment]
I will try with Celery once again, as I changed this code so many times, that I don't remember if I the exception was the same. :+1: 

Yes, the traceback is from GET request (API details of ScanResult, which was saved in another process).
Correct, I use a `tablename = 'Scans' in Scan model. 
I think that the problem is a connection which is stored in ScanResult model after using it in separate process, Weppy seems to not open it again in main process. But I am not sure.

This is what is get in browser when trying to get that ScanResult via API: 
```
def with_connection_or_raise(f):
    def wrap(*args, **kwargs):
        if not args[0].connection:
            if len(args) > 1:
                raise ValueError(args[1])  # this one is raised
            raise RuntimeError('no connection available')
        return f(*args, **kwargs)
    return wrap
```

**Comment by gi0baro** [comment]
@guy881 as far as I used and tested in several environment, the ORM and its connection should be both process-fork and thread safe.

I suspect the error you got depends on something wrong in the way code or your request/background flow is structured.

**Comment by guy881** [comment]
I finally got it working with celery! :) It's a shame I cannot do it with multiprocessing as the code will be running on Raspberry Pi and celery seems overwhelming, but I am glad it's working at all. :)
Thank you very much @gi0baro, for your time and priceless help.

Best wishes!
