### ISSUE TITLE
Cannot import form from outside

### ISSUE THREAD

**Issue by bisguzar** [gi0baro/weppy#222]
Hello, I created a forms.py file and put my forms into it. When I tried import these I except 

> /home/bisguzar/mergen/bin/python /home/bisguzar/Chest/projects/mergen/app.py
> Traceback (most recent call last):
>   File "/home/bisguzar/Chest/projects/mergen/app.py", line 8, in <module>
>     import forms
>   File "/home/bisguzar/Chest/projects/mergen/forms.py", line 10, in <module>
>     formstyle = SemanticUI
>   File "/home/bisguzar/mergen/lib/python3.6/site-packages/weppy/forms.py", line 58, in __init__
>     self._preprocess_(**kwargs)
>   File "/home/bisguzar/mergen/lib/python3.6/site-packages/weppy/forms.py", line 67, in _preprocess_
>     'formstyle', self._get_default_style())
>   File "/home/bisguzar/mergen/lib/python3.6/site-packages/weppy/forms.py", line 35, in _get_default_style
>     return Expose.application.config.ui.forms_style or FormStyle
> AttributeError: 'NoneType' object has no attribute 'config'

I looked Expose object from shell and It has application attribute. It's not None

**Comment by gi0baro** [comment]
@bisguzar that's not the proper way, you should avoid to tamper with weppy internals.
A better way to fix this could be:
- import your forms module **after** defining application object
- import from your forms module the data you need directly in your routes or where you actually use them

**Comment by bisguzar** [comment]
@gi0baro yes, its better way. I want to know that do you have a live-communication channel? Like slack.
